feat: Detect the number of issues created that have a bounty
tscircuit/contribution-tracker pull request #17
Opened 2024-12-03 03:33 UTC by Anshgrover23

/claim #15
Fixes #15

2024-12-03 04:09 UTC, seveibar commented on lib/getBountiedIssues.ts
> +      since: startDate,
Hmm why not filter by tag

2024-12-03 04:09 UTC, seveibar commented on lib/getBountiedIssues.ts
> +      since: startDate,
I see you do it below, but wondering if its possible here to avoid pagination likits

2024-12-03 04:49 UTC, Anshgrover23 commented on lib/getBountiedIssues.ts
> +      since: startDate,
I’ve updated the code to filter issues by the 💎 Bounty label directly in the API call using the labels parameter. tell me if any further changes needed.

2024-12-03 07:12 UTC, seveibar requested changes
Can you demonstrate that this works and remove the package lock (we use bun in all projects)

2024-12-03 09:29 UTC, seveibar requested changes

2024-12-03 09:29 UTC, seveibar commented on scripts/test-github-issues.ts
> +): number {
Import code under test, dont redefine it

2024-12-03 09:29 UTC, seveibar commented on scripts/test-github-issues.ts
> +): number {
Goes for almost this entire file

2024-12-03 10:35 UTC, Anshgrover23 commented on scripts/test-github-issues.ts
> +): number {
@seveibar done.

2024-12-03 11:18 UTC, seveibar commented on lib/getBountiedIssues.ts
> +export async function fetchBountiedIssues(
Function name should match file name

2024-12-03 11:24 UTC, Anshgrover23 commented on lib/getBountiedIssues.ts
> +export async function fetchBountiedIssues(
done.

2024-12-03 13:10 UTC, seveibar commented on lib/getBountiedIssues.ts
> +        console.log(botComment?.body);
```suggestion
```

2024-12-03 13:11 UTC, seveibar commented
@Anshgrover23 can you show the result of actually generating the table? It's been broken in the past by people not fully testing, i'd like to make sure it actually generates the table properly.

2024-12-03 13:50 UTC, Anshgrover23 commented on lib/getBountiedIssues.ts
> +        console.log(botComment?.body);
done.

2024-12-03 13:53 UTC, seveibar commented
`bun scripts/generate-weekly-overview.ts` should do it.

Remember that when you PR code, it is expected that you've run the code, never PR code you haven't run.

I've actually only ever suspended one contributor from tscircuit, and it was for not running their code and repeatedly introducing bugs. So this is a very critical/important thing to do.

2024-12-03 17:09 UTC, imrishabh18 commented
@Anshgrover23 I don't think the data is correct, see the issues created column. It's 0 for all

2024-12-04 02:45 UTC, seveibar approved these changes

2024-12-04 02:46 UTC, merged